export const SEARCH_DOSSIER_A_SUIVRE = "SEARCH_DOSSIER_A_SUIVRE";
export const SEARCH_DOSSIER_A_SUIVRE_ADMIN = "SEARCH_DOSSIER_A_SUIVRE_ADMIN";
export const PERSONNELOGIN = "PERSONNELOGIN";
export const PROJETSBYARCHITECTE = "PROJETSBYARCHITECTE";
export const GET_ALL_AGENCES = "GET_ALL_AGENCES";
export const GET_CONTIBUTIONS_FOR_GRAND_PROJET =
  "GET_CONTIBUTIONS_FOR_GRAND_PROJET";
export const GET_EVERYTHING = "GET_EVERYTHING";
export const GET_ALL_PROJETS_FOR_ADMIN = "GET_ALL_PROJETS_FOR_ADMIN";
export const GET_CONTIBUTIONS_FOR_GRAND_PROJET_ADMIN =
  "GET_CONTIBUTIONS_FOR_GRAND_PROJET_ADMIN";
